webapp/main/routes.py
from flask import render_template, url_for, redirect, Blueprint
from flask_login import login_required, current_user
from webapp.example_values import *


main = Blueprint("main", __name__)


@main.route("/layout")
def layout():
    return render_template("base/layout.html")


@main.route("/")
def splash_page():
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))
    return render_template("main/splash.html")


@main.route("/dashboard")
@login_required
def dashboard():
    cards = [card_net_worth, card_nest_egg, card_fi_number, card_fi_date, card_fi_time]
    return render_template("main/dashboard.html", title="Dashboard", cards=cards, card_fi_percentage=card_fi_percentage)


@main.route("/portfolio")
@login_required
def portfolio():
    category_break
    cards = [card_net_worth, card_nest_egg, card_liabilities, card_open_credit, card_available_credit, card_cash_credit]
    return render_template("main/portfolio.html", title="Portfolio", category_break=category_break, cards=cards)


@main.route("/expenses")
@login_required
def expenses_page():
    table
    total
    return render_template("main/expenses.html", title="Expenses", table = table, total = total)


@main.route("/site_info")
def site_info():
    return render_template("main/site_info.html", title="Site Info")


@main.route("/financial_independence")
@login_required
def fi_page():
    averages = [avg_earnings, avg_savings, avg_savings_rate, investment_growth, growth_rate, avg_nw, avg_fi_perc]
    milestones = [milestone_first_100, milestone_coast_fi, milestone_half_fi, milestone_lean_fi, milestone_fi]
    return render_template("main/financial_independence.html", title="Financial Independence", averages=averages, milestones = milestones)


@main.route("/documents")
@login_required
def documents_page():
    return render_template("main/documents.html", title="Documents")

webapp/users/routes.py
import os
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from webapp import app, db, bcrypt
from webapp.models import User, Account
from webapp.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateProfileForm,
    SetPasswordForm,
)
from webapp.users.utils import save_picture, send_reset_email


users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pass = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(
            name=form.name.data,
            email=form.email.data,
            dob=form.dob.data,
            password=hashed_pass,
        )
        db.session.add(user)
        db.session.commit()
        flash(
            f"Profile created for {form.name.data}, you are now able to log in",
            "success",
        )
        return redirect(url_for("users.login"))
    return render_template("user/register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.dashboard"))
        else:
            flash("Login unsuccessful, please check email and password", "danger")
    return render_template("user/login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.dashboard"))


@users.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    form = UpdateProfileForm()
    if form.validate_on_submit():
        if form.picture.data:
            old_pic = current_user.profile_pic
            picture_file = save_picture(form.picture.data, str(current_user.id))
            current_user.profile_pic = picture_file
            if old_pic != "default.jpg":
                os.remove(os.path.join(app.root_path, "static", "profile_pics", old_pic))

        current_user.name = form.name.data
        current_user.email = form.email.data
        current_user.dob = form.dob.data
        db.session.commit()
        flash("Your profile has been updated!", "success")
        return redirect(url_for("users.profile"))
    elif request.method == "GET":
        form.name.data = current_user.name
        form.email.data = current_user.email
        form.dob.data = current_user.dob

    return render_template("user/profile.html", title="Profile", form=form)


#not yet completed
@users.route("/set_password", methods=["GET", "POST"])
def set_password():
    form = SetPasswordForm()
    if form.validate_on_submit():
        if current_user:
            current_user.password=bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        else:
            #presumably there is no 'current_user' if the user follows a forgotten password link
            return
        db.session.commit()
        flash(
            f"Password changed successfully",
            "success",
        )
        return redirect(url_for("users.login"))
    return render_template("user/set_password.html", form=form, title="Set Password")

webapp/templates/base/footer.html
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center pt-3 pb-3 mt-3 border-top">
        <div class="col-md-3 d-flex align-items-center">
            <a class="navbar-brand" href="{{ url_for('main.site_info') }}">Site Info</a>
        </div>

        <div class="col-md-3 d-flex justify-content-end">
            <a href="https://github.com/samjprice/financial_dashboard" class="ms-1 text-decoration-none" target="_blank" rel="noreferrer noopener">
                <img src="/static/GitHub/GitHub_Logo.png" alt="GitHub" height="25">
                <img src="/static/GitHub/GitHub-Mark-32px.png" alt="GitHub Logo" height="25" width="25">
            </a>
          </div>
    </footer>
  </div>

webapp/templates/base/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Dynamic Title -->
    {% if title %}
        <title> FinDash - {{title}} </title>
    {% else %}
        <title> Financial Dashboard </title>
    {% endif %}

    <!-- Bootstrap CSS via delivery network -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <!-- Bootstrap CSS for Nav bar -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
</head>

<body class="d-flex flex-column min-vh-100">

    <!-- Navigation bar (top) -->
    <header class="site header mb-2">
        {% include 'base/nav-top.html' %}
    </header>

    <!-- Main Content -->
    <main class="d-flex flex-nowrap">
        <div class="container-fluid">
            <div class="row">
                
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}   

            </div>
            <div class="row">
                <h1 class="mb-4">{{title}}</h1>
                {% block content %}{% endblock content %}
            </div>
        </div>
    </main>

    <!-- Bootstrap JavaScript via delivery network -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <!-- Footer -->
    <footer class='mt-auto'>
        {% include 'base/footer.html' %}
    </footer>

</body>
</html>

webapp/templates/base/nav-top.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
        
        <!-- Navbar brand -->
        <a class="navbar-brand" href="{{url_for('main.dashboard')}}">Financial Dashboard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">

        <!-- Nav links -->
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.portfolio') }}">Portfolio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.expenses_page') }}">Expenses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.fi_page') }}">FI</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-bs-toggle="dropdown" aria-expanded="false">Tools</a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown03">
                    <li><a class="dropdown-item" href="{{ url_for('accounts.accounts_page') }}">Accounts Information</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('main.documents_page') }}">Important Documents</a></li>
                    <li><a class="dropdown-item" href="####################################">Compound Interest Calculator</a></li>
                    <li><a class="dropdown-item" href="####################################">Sinking Funds</a></li>
                </ul>
            </li>
        </ul>

        <!-- User functions -->
        <div class="navbar-nav">
            {% if current_user.is_authenticated %}
                <div class="flex-shrink-0 dropdown">
                    <a class="d-block link-light dropdown-toggle" href="#" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ current_user.name }}
                        <img src="{{url_for('static', filename='profile_pics/' + current_user.profile_pic)}}" alt="{{ current_user.name }}" width="32" height="32" class="rounded-circle mx-1">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown03">
                        <li><a class="dropdown-item" href="{{ url_for('users.profile') }}">Profile</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a></li>
                    </ul>
                </div>
            {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>